/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {

    public int[] roll(int n) {
        
        Random randNum = new Random();
        int[] dice = new int[n];
        
        for (int i = 0; i < n; i++) {
            int roll = randNum.nextInt(6) + 1;
            dice[i] = roll;
        }
        return dice;
    }
}