/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class Business {
    ///// FIELD/PROPERTIES /////
    String name;
    int price;
    float star = 0.0f;
    float averageStarRating = 0;
    int totalBusinessReviews = 0;
    ArrayList<Review> reviewList = new ArrayList<>();


    ///// CONSTRUCTOR /////
    public Business(String name, int price) {
        this.name = name;
        this.price = price;
    }


    ///// ADD REVIEW /////
    public Review addReview(Review review) {
        reviewList.add(review);
        this.star += review.stars;
        this.totalBusinessReviews++;
        this.averageStarRating = (float) (this.star) / (float) (totalBusinessReviews);
        return review;
    }

    ///// STRING /////
        @Override
        public String toString () {
            return "Business- " +
                    "Name: '" + name + '\'' +
                    ", Price: $" + price +
                    ", Total Stars: " + star +
                    ", Average Star Rating: " + averageStarRating +
                    ", Toatal Business Reviews: " + totalBusinessReviews +
                    ", Reviews: " + reviewList;
        }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public float getStar() {
        return star;
    }

    public void setStar(float star) {
        this.star = star;
    }

    public float getAverageStarRating() {
        return averageStarRating;
    }

    public void setAverageStarRating(float averageStarRating) {
        this.averageStarRating = averageStarRating;
    }

    public int getTotalBusinessReviews() {
        return totalBusinessReviews;
    }

    public void setTotalBusinessReviews(int totalBusinessReviews) {
        this.totalBusinessReviews = totalBusinessReviews;
    }

    public ArrayList<Review> getReviews() {
        return reviewList;
    }

    public void setReviews(ArrayList<Review> reviews) {
        this.reviewList = reviews;
    }
}



