/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class Business {
    String name;

    String dollar = "$";
    int price = 0;
    float star = 0.0f;
    float averageStarRating = 0;
    int totalBusinessReviews = 0;

    public Business(String name, int price) {
        this.name = name;
        this.price = price;
    }

    public String toString(){
        String str = "";
        str += "Name:" + this.name + "Price: $" + this.price;
        return str;
    }

}



